version: '3.8'
services:
  mysql-master:
    container_name: mysql-master
    image: mysql:5.7
    restart: always
    ports:
      - "3340:3306"
    privileged: true
    volumes:
      - ./msql-master/volumes/log:/var/log/mysql
      - ./msql-master/volumes/conf/my.cnf:/etc/mysql/my.cnf
      - ./msql-master/volumes/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--max_connections=3000'
    ]
    networks:
      - mynet

  mysql-slave:
    container_name: mysql-slave
    image: mysql:5.7
    restart: always
    ports:
      - "3341:3306"
    privileged: true
    volumes:
      - ./msql-slave/volumes/log:/var/log/mysql
      - ./msql-slave/volumes/conf/my.cnf:/etc/mysql/my.cnf
      - ./msql-slave/volumes/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--max_connections=3000'
    ]
    networks:
      - mynet

networks:
  mynet:
    external: true
